import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

import AuthProvider from "./context/auth-provider";

import "./globals.css";

const quicksandFont = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={quicksandFont.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
